import React from "react";
import { MODELS } from "../../services/imageApi";
import "./ImageGrid.scss";

const ImageGrid = ({ images, isGenerating, errors }) => {
  const models = Object.values(MODELS); // Only 2 models now

  const renderImageContent = (model) => {
    if (isGenerating) {
      return (
        <div className="loading">
          <div className="spinner"></div>
          <p>Generating...</p>
        </div>
      );
    }

    if (errors && errors[model.name]) {
      return (
        <div className="error-state">
          <span className="error-icon">⚠️</span>
          <p className="error-message">{errors[model.name]}</p>
        </div>
      );
    }

    if (images && images[model.name]) {
      return (
        <div className="image-wrapper">
          <img
            src={images[model.name]}
            alt={`Generated by ${model.displayName}`}
            onError={(e) => {
              console.error("Image load error:", e);
              e.target.onerror = null;
            }}
          />
          <div className="image-overlay">
            <a
              href={images[model.name]}
              download={`${model.name}-image.png`}
              className="download-btn"
            >
              ⬇ Download
            </a>
          </div>
        </div>
      );
    }

    return (
      <div className="placeholder">
        <p>Image will appear here</p>
      </div>
    );
  };

  return (
    <div className="outputs-section">
      <h2>Generated Images</h2>
      <div className="models-grid">
        {models.map((model) => (
          <div key={model.name} className="model-card">
            <h3>{model.displayName}</h3>
            <div className="image-container">{renderImageContent(model)}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ImageGrid;
